# Generated by Django 4.1.4 on 2022-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorinst', models.CharField(max_length=255, verbose_name='Директор')),
                ('directorfiliala', models.CharField(max_length=255, verbose_name='Дирекция института')),
                ('group', models.CharField(max_length=30, verbose_name='Номер группы')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО студента(ки)')),
                ('vsvazy', models.CharField(max_length=30, verbose_name='Причина заявления')),
                ('doc1', models.CharField(max_length=30, verbose_name='Допумент 1')),
                ('doc2', models.CharField(max_length=30, verbose_name='Документ 2')),
                ('doc3', models.CharField(max_length=30, verbose_name='Документ 3')),
                ('d', models.CharField(max_length=30, verbose_name='День')),
                ('month', models.CharField(max_length=30, verbose_name='Месяц')),
                ('year', models.CharField(max_length=30, verbose_name='Год')),
                ('nasnachits', models.CharField(max_length=30, verbose_name='Первый день')),
                ('nasnachitpo', models.CharField(max_length=30, verbose_name='Последний день')),
                ('nasnachenas', models.CharField(max_length=30, verbose_name='Первый день до заявления')),
                ('nasnachenapo', models.CharField(max_length=30, verbose_name='Последний день до заявления')),
                ('dp', models.CharField(max_length=30, verbose_name='День приказа')),
                ('monthp', models.CharField(max_length=30, verbose_name='Месяц приказа')),
                ('yearp', models.CharField(max_length=30, verbose_name='Год приказа')),
                ('directorinstf', models.CharField(max_length=30, verbose_name='Дирекция')),
                ('fio2', models.CharField(max_length=30, verbose_name='ФИО директора')),
                ('d2', models.CharField(max_length=30, verbose_name='Дата согласования')),
                ('month2', models.CharField(max_length=30, verbose_name='Месяц согласования')),
                ('year2', models.CharField(max_length=30, verbose_name='Год согласования')),
            ],
        ),
    ]
