# Generated by Django 4.1.4 on 2022-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liblinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=150, verbose_name='Авторы')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('num_izd', models.CharField(max_length=150, verbose_name='Номер издания')),
                ('city', models.CharField(max_length=150, verbose_name='Город издания')),
                ('izdatelstvo', models.CharField(max_length=150, verbose_name='Издательство')),
                ('year', models.CharField(max_length=150, verbose_name='Год издания')),
                ('total', models.CharField(max_length=150, verbose_name='Общее число страниц в книге')),
            ],
        ),
    ]
