# Generated by Django 4.1.4 on 2022-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaf', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('name_work', models.CharField(max_length=255, verbose_name='Название работы')),
                ('num_list', models.CharField(max_length=30, verbose_name='Номер листов')),
                ('podp1', models.CharField(max_length=30, verbose_name='Подпись 1')),
                ('prepod', models.CharField(max_length=30, verbose_name='Препод')),
                ('group', models.CharField(max_length=30, verbose_name='Группа')),
                ('d1', models.CharField(max_length=30, verbose_name='День проверки')),
                ('m1', models.CharField(max_length=30, verbose_name='Месяц проверки')),
                ('year1', models.CharField(max_length=30, verbose_name='Год проверки')),
                ('podp2', models.CharField(max_length=30, verbose_name='Подпись 2')),
                ('student', models.CharField(max_length=30, verbose_name='Студент')),
                ('d2', models.CharField(max_length=30, verbose_name='День сдачи')),
                ('m2', models.CharField(max_length=30, verbose_name='Месяц сдачи')),
                ('year2', models.CharField(max_length=30, verbose_name='Год сдачи')),
            ],
        ),
    ]
